version: "3.2"

services:
  upload-microservice:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3035:3035"
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
      - type: bind
        source: ./local/files
        target: /usr/src/app/local/files
